#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mraa
Version  : 2.0.0
Release  : 2
URL      : https://github.com/intel-iot-devkit/mraa/archive/v2.0.0.tar.gz
Source0  : https://github.com/intel-iot-devkit/mraa/archive/v2.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause BSL-1.0 LGPL-2.1 MIT
Requires: mraa-bin = %{version}-%{release}
Requires: mraa-data = %{version}-%{release}
Requires: mraa-lib = %{version}-%{release}
Requires: mraa-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : git
BuildRequires : googletest-dev
BuildRequires : pkgconfig(udev)
BuildRequires : python3
BuildRequires : python3-dev

%description
These headers was automatically generated from a Linux kernel header
of the same name, to make information necessary for userspace to
call into the kernel available to libc.  It contains only constants,
structures, and macros generated from the original header, and thus,
contains no copyrightable information.

%package bin
Summary: bin components for the mraa package.
Group: Binaries
Requires: mraa-data = %{version}-%{release}
Requires: mraa-license = %{version}-%{release}

%description bin
bin components for the mraa package.


%package data
Summary: data components for the mraa package.
Group: Data

%description data
data components for the mraa package.


%package dev
Summary: dev components for the mraa package.
Group: Development
Requires: mraa-lib = %{version}-%{release}
Requires: mraa-bin = %{version}-%{release}
Requires: mraa-data = %{version}-%{release}
Provides: mraa-devel = %{version}-%{release}

%description dev
dev components for the mraa package.


%package lib
Summary: lib components for the mraa package.
Group: Libraries
Requires: mraa-data = %{version}-%{release}
Requires: mraa-license = %{version}-%{release}

%description lib
lib components for the mraa package.


%package license
Summary: license components for the mraa package.
Group: Default

%description license
license components for the mraa package.


%prep
%setup -q -n mraa-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538085614
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1538085614
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mraa
cp COPYING %{buildroot}/usr/share/package-licenses/mraa/COPYING
cp cmake/modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/mraa/cmake_modules_COPYING-CMAKE-SCRIPTS
cp cmake/modules/Copyright.txt %{buildroot}/usr/share/package-licenses/mraa/cmake_modules_Copyright.txt
cp cmake/modules/LICENSE.LGPL %{buildroot}/usr/share/package-licenses/mraa/cmake_modules_LICENSE.LGPL
cp cmake/modules/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/mraa/cmake_modules_LICENSE_1_0.txt
cp src/i2c/LICENSE %{buildroot}/usr/share/package-licenses/mraa/src_i2c_LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mraa-gpio
/usr/bin/mraa-i2c
/usr/bin/mraa-uart

%files data
%defattr(-,root,root,-)
/usr/share/mraa/examples/CMakeLists.txt
/usr/share/mraa/examples/c++/CMakeLists.txt
/usr/share/mraa/examples/c++/aio.cpp
/usr/share/mraa/examples/c++/gpio.cpp
/usr/share/mraa/examples/c++/gpio_advanced.cpp
/usr/share/mraa/examples/c++/i2c.cpp
/usr/share/mraa/examples/c++/iio.cpp
/usr/share/mraa/examples/c++/led.cpp
/usr/share/mraa/examples/c++/pwm.cpp
/usr/share/mraa/examples/c++/spi.cpp
/usr/share/mraa/examples/c++/uart.cpp
/usr/share/mraa/examples/c++/uart_ow.cpp
/usr/share/mraa/examples/c/CMakeLists.txt
/usr/share/mraa/examples/c/aio.c
/usr/share/mraa/examples/c/gpio.c
/usr/share/mraa/examples/c/gpio_advanced.c
/usr/share/mraa/examples/c/hellomraa.c
/usr/share/mraa/examples/c/i2c_hmc5883l.c
/usr/share/mraa/examples/c/i2c_mpu6050.c
/usr/share/mraa/examples/c/iio.c
/usr/share/mraa/examples/c/initio.c
/usr/share/mraa/examples/c/led.c
/usr/share/mraa/examples/c/pwm.c
/usr/share/mraa/examples/c/spi.c
/usr/share/mraa/examples/c/uart.c
/usr/share/mraa/examples/c/uart_advanced.c
/usr/share/mraa/examples/c/uart_ow.c
/usr/share/mraa/examples/gpio_multiple_rw.c
/usr/share/mraa/examples/java/AioA0.java
/usr/share/mraa/examples/java/BlinkIO.java
/usr/share/mraa/examples/java/BlinkOnboard.java
/usr/share/mraa/examples/java/Bmp85.java
/usr/share/mraa/examples/java/CyclePwm3.java
/usr/share/mraa/examples/java/Example.java
/usr/share/mraa/examples/java/FTDITest.java
/usr/share/mraa/examples/java/GpioMmapped.java
/usr/share/mraa/examples/java/GpioRead6.java
/usr/share/mraa/examples/java/HelloEdison.java
/usr/share/mraa/examples/java/I2cCompass.java
/usr/share/mraa/examples/java/Isr.java
/usr/share/mraa/examples/java/SpiMAX7219.java
/usr/share/mraa/examples/java/SpiMCP4261.java
/usr/share/mraa/examples/java/UartExample.java
/usr/share/mraa/examples/javascript/AioA0.js
/usr/share/mraa/examples/javascript/Blink-IO.js
/usr/share/mraa/examples/javascript/GPIO_DigitalRead.js
/usr/share/mraa/examples/javascript/GPIO_DigitalWrite.js
/usr/share/mraa/examples/javascript/bmp85.js
/usr/share/mraa/examples/javascript/firmata.js
/usr/share/mraa/examples/javascript/gpio-tool.js
/usr/share/mraa/examples/javascript/initio.js
/usr/share/mraa/examples/javascript/isr.js
/usr/share/mraa/examples/javascript/rgblcd.js
/usr/share/mraa/examples/javascript/spi.js
/usr/share/mraa/examples/javascript/uart.js
/usr/share/mraa/examples/platform/CMakeLists.txt
/usr/share/mraa/examples/platform/Up2Leds.java
/usr/share/mraa/examples/platform/firmata_curie_imu.c
/usr/share/mraa/examples/platform/gpio_edison.c
/usr/share/mraa/examples/platform/i2c_firmata.c
/usr/share/mraa/examples/platform/initio.c
/usr/share/mraa/examples/platform/initio.cpp
/usr/share/mraa/examples/platform/initio.py
/usr/share/mraa/examples/platform/intel-aero.json
/usr/share/mraa/examples/platform/turbotjson.json
/usr/share/mraa/examples/platform/up2-leds.cpp
/usr/share/mraa/examples/python/aio.py
/usr/share/mraa/examples/python/firmata.py
/usr/share/mraa/examples/python/gpio.py
/usr/share/mraa/examples/python/gpio_advanced.py
/usr/share/mraa/examples/python/i2c_bmp85.py
/usr/share/mraa/examples/python/i2c_rgb.py
/usr/share/mraa/examples/python/led.py
/usr/share/mraa/examples/python/pwm.py
/usr/share/mraa/examples/python/spi.py
/usr/share/mraa/examples/python/spi_loopback.py
/usr/share/mraa/examples/python/uart.py
/usr/share/mraa/examples/python/uart_receiver.py
/usr/share/mraa/examples/python/uart_sender.py
/usr/share/mraa/examples/samples.mapping.txt
/usr/share/package-licenses/mraa/cmake_modules_Copyright.txt

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/*.hpp
/usr/include/mraa/aio.h
/usr/include/mraa/aio.hpp
/usr/include/mraa/common.h
/usr/include/mraa/common.hpp
/usr/include/mraa/firmata.h
/usr/include/mraa/gpio.h
/usr/include/mraa/gpio.hpp
/usr/include/mraa/i2c.h
/usr/include/mraa/i2c.hpp
/usr/include/mraa/iio.h
/usr/include/mraa/iio.hpp
/usr/include/mraa/iio_kernel_headers.h
/usr/include/mraa/initio.h
/usr/include/mraa/initio.hpp
/usr/include/mraa/led.h
/usr/include/mraa/led.hpp
/usr/include/mraa/pwm.h
/usr/include/mraa/pwm.hpp
/usr/include/mraa/spi.h
/usr/include/mraa/spi.hpp
/usr/include/mraa/types.h
/usr/include/mraa/types.hpp
/usr/include/mraa/uart.h
/usr/include/mraa/uart.hpp
/usr/include/mraa/uart_ow.h
/usr/include/mraa/uart_ow.hpp
/usr/lib64/libmraa.so
/usr/lib64/pkgconfig/mraa.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmraa.so.2
/usr/lib64/libmraa.so.2.0.0

%files license
%defattr(-,root,root,-)
/usr/share/package-licenses/mraa/COPYING
/usr/share/package-licenses/mraa/cmake_modules_COPYING-CMAKE-SCRIPTS
/usr/share/package-licenses/mraa/cmake_modules_LICENSE.LGPL
/usr/share/package-licenses/mraa/cmake_modules_LICENSE_1_0.txt
/usr/share/package-licenses/mraa/src_i2c_LICENSE
